import {ENGINES,defaults,renderEngine,inkPresetValues,ORIGIN_LABELS} from './engines.js';
import {ellipse,canvas} from './geometry.js';
import {ContourEditor} from './contour-editor.js';
import {createPresets} from './presets.js';
import {DEFAULT_LAYOUT,normalizeLayout} from './layout-model.js';
import {createLayoutEditor} from './layout-editor.js';
const $=s=>document.querySelector(s),clone=s=>structuredClone(s),key='hydrofoooil-art-libraries-v3';
const photoImages=new Map();let photos=[];
let state={layout:normalizeLayout(DEFAULT_LAYOUT),version:3,photoId:'original',engine:'ink',points:ellipse(),smooth:75,feather:0,interior:true,seed:7319,quality:1000,options:Object.fromEntries(ENGINES.map(e=>[e.id,defaults(e.id)]))},photo,mask,snapshot,mode='photo',revision=0,busy=false,timer,editor,modeBeforeDrawing,presets,layoutEditor,renderPending=false;
function normalize(input){if(!input||input.version!==3||!ENGINES.some(e=>e.id===input.engine))throw new Error('需要版本 3 的工作台参数');if(!Array.isArray(input.points)||input.points.length<3||input.points.length>80||input.points.some(p=>!Array.isArray(p)||p.length!==2||p.some(n=>typeof n!=='number'||!Number.isFinite(n)||n<0||n>1)))throw new Error('轮廓参数无效');const s={...state,...input,photoId:input.photoId??'original',options:{}};if(!photos.some(p=>p.id===s.photoId))throw new Error('未知照片');s.layout=normalizeLayout(input.layout?{...input.layout,links:input.layout.links??state.layout.links}:state.layout);s.points=clone(input.points);for(const e of ENGINES){s.options[e.id]={};for(const c of e.controls){const v=input.options?.[e.id]?.[c.key]??c.value;if(c.values){if(!c.values.includes(v))throw new Error('未知笔刷选项');s.options[e.id][c.key]=v;}else{if(typeof v!=='number'||!Number.isFinite(v)||v<c.min||v>c.max)throw new Error('效果参数超出范围');s.options[e.id][c.key]=v;}}}for(const [k,min,max]of [['smooth',0,100],['feather',0,12],['seed',1,2147483646]])if(!Number.isFinite(s[k])||s[k]<min||s[k]>max)throw new Error('共同参数无效');s.seed=Math.round(s.seed);s.interior=!!s.interior;s.quality=[700,1000,1400].includes(+s.quality)?+s.quality:1000;return s;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4500);}
function persist(){try{localStorage.setItem(key,JSON.stringify(state));}catch{}}
function ready(){return !busy&&!renderPending&&!editor?.drawing&&!!mask&&JSON.stringify(snapshot)===JSON.stringify(state);}
function updateActions(){for(const id of ['apply','export-mask','export-photo','export-svg'])$('#'+id).disabled=!ready();presets?.sync();layoutEditor?.syncArtwork();}
function changeLayout(value){state.layout=normalizeLayout(value);if(snapshot)snapshot.layout=clone(state.layout);persist();updateActions();}
function invalidate(delay=180){revision++;renderPending=true;snapshot=null;presets?.sync();for(const id of ['apply','export-mask','export-photo','export-svg'])$('#'+id).disabled=true;persist();$('#status').textContent='参数已更改，等待生成…';clearTimeout(timer);timer=setTimeout(generate,delay);}
async function generate(){if(!photo||busy)return;busy=true;renderPending=false;presets?.sync();const rev=revision,s=clone(state),start=performance.now();$('#loading').hidden=false;$('#loading').textContent=`${ENGINES.find(e=>e.id===s.engine).name} 正在生成…`;$('#status').textContent='生成中…';
 try{const result=await renderEngine(s,s.quality,Math.round(s.quality*photo.height/photo.width));if(rev===revision){mask=result;snapshot={...s,layout:clone(state.layout)};display();$('#status').textContent=`${ENGINES.find(e=>e.id===s.engine).name} · ${(performance.now()-start).toFixed(0)} ms · ${s.points.length} 个轮廓节点`;for(const id of ['apply','export-mask','export-photo','export-svg'])$('#'+id).disabled=editor.drawing;}}
 catch(e){console.error(e);if(rev===revision){$('#status').textContent='生成失败：'+e.message;toast(e.message+'；可点击重新生成');}}
 finally{busy=false;$('#loading').hidden=true;if(rev!==revision&&renderPending)generate();else updateActions();}}
function display(){if(!photo)return;const c=canvas(state.quality,Math.round(state.quality*photo.height/photo.width)),ctx=c.getContext('2d',{willReadFrequently:true});ctx.imageSmoothingQuality='high';if(mode==='original')ctx.drawImage(photo,0,0,c.width,c.height);else if(mask){if(mode==='mask')ctx.drawImage(mask,0,0,c.width,c.height);else{ctx.drawImage(photo,0,0,c.width,c.height);ctx.globalCompositeOperation='destination-in';ctx.drawImage(mask,0,0,c.width,c.height);}}$('#preview').src=c.toDataURL();layoutEditor?.syncArtwork();}
function fitStage(){if(!photo)return;const rect=$('#board').getBoundingClientRect(),ratio=photo.width/photo.height;$('#stage').style.aspectRatio=`${photo.width} / ${photo.height}`;$('#stage').style.width=Math.min(rect.width-22,(rect.height-22)*ratio)+'px';}
function photoInfo(){const entry=photos.find(p=>p.id===state.photoId);$('#photo-select').value=state.photoId;$('#photo-filename').textContent=entry.filename;$('#resolution').textContent=`照片 ${photo.width} × ${photo.height}`;fitStage();}
function choosePhoto(id){const selected=photoImages.get(id);if(!selected)throw new Error('照片尚未载入');if(selected===photo){photoInfo();return;}editor.cancelDrawing();photo=selected;state.photoId=id;state.width=photo.width;state.height=photo.height;mask=null;snapshot=null;editor.refresh();photoInfo();display();invalidate(0);}
function setOutlineVisibility(visible){
 editor.enabled=visible;$('#show-outline').checked=visible;$('#edit').classList.toggle('active',visible);$('#edit').setAttribute('aria-pressed',visible);editor.refresh();
 try{localStorage.setItem('hydrofoooil-art-show-outline',String(visible));}catch{}
}
function drawingMode(active,message){
 if(active&&modeBeforeDrawing===undefined){modeBeforeDrawing=mode;mode='original';}
 else if(!active&&modeBeforeDrawing!==undefined){mode=modeBeforeDrawing;modeBeforeDrawing=undefined;}
 $('#draw').classList.toggle('active',active);$('#draw').setAttribute('aria-pressed',active);$('#draw').disabled=active;$('#draw').textContent=active?'正在绘制轮廓…':'重新绘制轮廓';$('#cancel-draw').hidden=!active;
 $('#show-outline').checked=editor.enabled;$('#show-outline').disabled=active;$('#edit').classList.toggle('active',editor.enabled);$('#edit').setAttribute('aria-pressed',editor.enabled);$('#edit').disabled=$('#ellipse').disabled=$('#render').disabled=active;
 $('#undo').disabled=active||!editor.history.length;$('#redo').disabled=active||!editor.future.length;
 document.querySelectorAll('[data-mode]').forEach(b=>{b.disabled=active;b.classList.toggle('active',b.dataset.mode===mode);});
 $('#contour-hint').textContent=active?(message||'按住鼠标或手指，在原图上画出新的轮廓；松开自动闭合并生成效果。按 Esc 或点击「取消绘制」保留原轮廓。'):'要从头画，点击「重新绘制轮廓」，按住鼠标画一圈，松开自动闭合。也可拖动圆点、双击线条加点或双击圆点删点。';
 updateActions();display();
}
function control(schema,value,onChange,container){const row=document.createElement('div');row.className='control';const label=document.createElement('label');label.className='control-label';label.textContent=schema.label+(schema.origin?.type==='adapter'?'（工作台）':'');const id='control-'+schema.key+'-'+container.id;label.htmlFor=id;row.append(label);let input;
 if(schema.values){input=document.createElement('select');schema.values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;input.append(o);});input.value=value;input.onchange=()=>onChange(input.value);}
 else{const out=document.createElement('output');out.textContent=value;label.append(out);input=document.createElement('input');Object.assign(input,{type:'range',min:schema.min,max:schema.max,step:schema.step||1,value});input.oninput=()=>{out.textContent=input.value;onChange(+input.value);};}input.id=id;input.dataset.key=schema.key;row.dataset.control=schema.key;row.append(input);container.append(row);}
function sourceDetails(engine){const list=$('#parameter-source-list');list.replaceChildren();for(const c of engine.controls){const li=document.createElement('li'),strong=document.createElement('strong'),description=document.createElement('span');strong.textContent=c.label+' · '+ORIGIN_LABELS[c.origin.type];description.textContent=c.origin.api;li.append(strong,description);list.append(li);}if(engine.id==='ink')$('#engine-note').textContent+=' 选择预设会恢复该预设的原生参数；颜色统一为蒙版用黑色。';if(engine.id==='hokusai'||engine.id==='freehand')$('#engine-note').textContent+=' 沿轮廓自动运行，固定压感输入，不等同真实手写笔迹。';}
function controls(){const e=ENGINES.find(e=>e.id===state.engine);$('#engine-name').textContent=e.name;$('#engine-source').href=e.url;$('#controls').replaceChildren();e.controls.forEach(c=>control(c,state.options[e.id][c.key],v=>{state.options[e.id][c.key]=v;if(e.id==='ink'&&c.key==='preset'){Object.assign(state.options.ink,inkPresetValues(v));controls();}else if(c.values)visibility();invalidate();},$('#controls')));$('#common-controls').replaceChildren();for(const s of [{key:'smooth',label:'轮廓曲线平滑',min:0,max:100},{key:'feather',label:'蒙版羽化',min:0,max:12,step:.5}])control(s,state[s.key],v=>{state[s.key]=v;if(s.key==='smooth')editor.coordinates();invalidate();},$('#common-controls'));$('#interior').checked=state.interior;$('#seed').value=state.seed;$('#seed-row').hidden=!e.seed;$('#quality').value=state.quality;$('#engine-note').textContent=e.edge?'此库沿你画的轮廓绘制原生笔迹；内部填充由共同设置控制。':e.id==='aquarelle'?'使用原库水彩着色器。原库噪声尺度固定，可编辑输入轮廓并调节扩展。':e.id==='washes'?'真实水与颜料模拟。每次重新生成可能有自然变化，导出会保留当前这一次结果。':'此库直接绘制自定义封闭轮廓，关闭内部填充可保留原生纹理。';sourceDetails(e);visibility();layoutEditor?.sync();for(const b of document.querySelectorAll('.engine-card')){const active=b.dataset.engine===state.engine;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);}}
function visibility(){const o=state.options[state.engine];for(const row of document.querySelectorAll('#controls .control')){const k=row.dataset.control;let hidden=false;if(state.engine==='p5')hidden=o.variant==='水彩填充'?k==='width':['bleed','texture','border','opacity'].includes(k);if(state.engine==='fabric')hidden=o.variant!=='SprayBrush'&&['density','dot','variance','opacity'].includes(k);row.hidden=hidden;}}
function choose(id){if(id===state.engine)return;state.engine=id;controls();invalidate(0);}
function full(mode){if(!ready())throw new Error('请等待当前效果生成完成');const c=canvas(photo.width,photo.height),ctx=c.getContext('2d');if(mode==='photo'){ctx.drawImage(photo,0,0);ctx.globalCompositeOperation='destination-in';}ctx.drawImage(mask,0,0,c.width,c.height);return c;}
function restoreSettings(input,savedMask){
 const next=normalize(input),selectedPhoto=photoImages.get(next.photoId),height=Math.round(next.quality*selectedPhoto.height/selectedPhoto.width);
 if(savedMask&&(savedMask.width!==next.quality||savedMask.height!==height))throw new Error('方案蒙版尺寸不匹配');
 editor.cancelDrawing();clearTimeout(timer);revision++;renderPending=false;
 state=next;photo=selectedPhoto;state.width=photo.width;state.height=photo.height;
 editor.history=[];editor.future=[];$('#undo').disabled=$('#redo').disabled=true;editor.refresh();controls();photoInfo();
 mask=savedMask?canvas(state.quality,height):null;snapshot=null;
 if(savedMask){mask.getContext('2d').drawImage(savedMask,0,0);snapshot=clone(state);$('#loading').hidden=true;$('#status').textContent=ENGINES.find(e=>e.id===state.engine).name+' · 已恢复保存的蒙版';persist();display();updateActions();}
 else{display();invalidate(0);}
}
function download(data,name,type){const blob=typeof data==='string'?new Blob([data],{type}):data,url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function svg(url){return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${photo.width}" height="${photo.height}" viewBox="0 0 ${photo.width} ${photo.height}"><image width="${photo.width}" height="${photo.height}" xlink:href="${url}"/></svg>`;}
async function exportPng(mode){try{full(mode).toBlob(b=>download(b,`hydrofoooil-${state.photoId}-${mode}.png`),'image/png');}catch(e){toast(e.message);}}
async function init(){try{const config=await fetch('/api/config').then(r=>r.json());photos=config.photos;state.layout=normalizeLayout(config.homepageLayout??DEFAULT_LAYOUT);await Promise.all(photos.map(async entry=>{const image=new Image();image.src=entry.url;await image.decode();photoImages.set(entry.id,image);}));for(const entry of photos){const option=document.createElement('option');option.value=entry.id;option.textContent=entry.label;$('#photo-select').append(option);}try{const stored=JSON.parse(localStorage.getItem(key)||'null');if(stored)state=normalize(stored);else if(config.saved?.version===3)state=normalize(config.saved);}catch(e){toast('旧参数无法读取，已使用新效果库的默认参数');}photo=photoImages.get(state.photoId);state.width=photo.width;state.height=photo.height;
 // Apply the requested Chinese font once to existing drafts; later choices remain user-controlled.
 try{const migration='hydrofoooil-chinese-stzhongsong-v1';if(!localStorage.getItem(migration)){state.layout.chinese.font='stzhongsong';persist();localStorage.setItem(migration,'true');}}catch{}
 editor=new ContourEditor($('#outline'),()=>state,(points,done)=>{state.points=points;if(done)invalidate(0);else{revision++;updateActions();}},(past,future)=>{$('#undo').disabled=editor.drawing||!past;$('#redo').disabled=editor.drawing||!future;},drawingMode);let showOutline=true;try{showOutline=localStorage.getItem('hydrofoooil-art-show-outline')!=='false';}catch{}setOutlineVisibility(showOutline);
 ENGINES.forEach(e=>{const b=document.createElement('button');b.className='engine-card';b.dataset.engine=e.id;const name=document.createElement('strong'),kind=document.createElement('small');name.textContent=e.name;kind.textContent=e.kind;b.append(name,kind);b.onclick=()=>choose(e.id);$('#engines').append(b);});controls();photoInfo();presets=createPresets({current:()=>({settings:clone(state),mask,ready:ready()}),restore:restoreSettings,photos,toast});layoutEditor=createLayoutEditor({readState:()=>state,artwork:()=>mask&&snapshot?{mask,photo,entry:photos.find(p=>p.id===state.photoId)}:null,onChange:changeLayout,toast});new ResizeObserver(fitStage).observe($('#board'));$('#photo-select').onchange=e=>choosePhoto(e.target.value);
 $('#interior').onchange=e=>{state.interior=e.target.checked;invalidate();};$('#seed').onchange=e=>{state.seed=Math.max(1,Math.min(2147483646,Math.round(+e.target.value)||1));e.target.value=state.seed;invalidate();};$('#reseed').onclick=()=>{state.seed=1+Math.floor(Math.random()*2147483645);$('#seed').value=state.seed;invalidate(0);};$('#quality').onchange=e=>{state.quality=+e.target.value;invalidate();};
 $('#reset-engine').onclick=()=>{state.options[state.engine]=defaults(state.engine);controls();invalidate(0);};$('#ellipse').onclick=()=>editor.set(ellipse());$('#undo').onclick=()=>editor.undo();$('#redo').onclick=()=>editor.redo();$('#edit').onclick=()=>setOutlineVisibility(!editor.enabled);$('#show-outline').onchange=e=>setOutlineVisibility(e.target.checked);$('#draw').onclick=()=>editor.startDrawing();$('#cancel-draw').onclick=()=>editor.cancelDrawing();document.addEventListener('keydown',e=>{if(e.key==='Escape'&&editor.drawing){e.preventDefault();editor.cancelDrawing();}});$('#render').onclick=()=>invalidate(0);
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(c=>c.classList.toggle('active',c===b));display();});document.querySelectorAll('[data-background]').forEach(b=>{if(b.tagName==='BUTTON')b.onclick=()=>{$('#board').dataset.background=b.dataset.background;document.querySelectorAll('.swatches button').forEach(c=>c.classList.toggle('active',c===b));};});
 $('#save-settings').onclick=()=>download(JSON.stringify(state,null,2)+'\n','hydrofoooil-art-settings.json','application/json');$('#import').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100000)throw new Error('参数文件太大');restoreSettings(JSON.parse(await f.text()));toast('已导入图片选择、轮廓和所有库的参数');}catch(err){toast(err.message);}finally{e.target.value='';}};
 $('#export-mask').onclick=()=>exportPng('mask');$('#export-photo').onclick=()=>exportPng('photo');$('#export-svg').onclick=()=>{try{download(svg(full('mask').toDataURL()),'hydrofoooil-mask.svg','image/svg+xml');}catch(e){toast(e.message);}};$('#apply').onclick=async()=>{try{const png=full('mask').toDataURL();$('#apply').disabled=true;const r=await fetch('/api/apply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({settings:snapshot,mask:png})}),body=await r.json();if(!r.ok)throw new Error(body.error);toast(body.message);}catch(e){toast(e.message);}finally{updateActions();}};
 window.artWorkbench={photos:photos.map(p=>({...p})),choosePhoto,engines:ENGINES.map(e=>e.id),get settings(){return clone(state);},get mask(){return mask;},get ready(){return ready();},choose,updateLayout:value=>{changeLayout(value);layoutEditor.sync();},setPoints:p=>editor.set(p),update:(values)=>{Object.assign(state.options[state.engine],values);controls();invalidate(0);},renderRaw:(s,w=700)=>renderEngine(s,w,Math.round(w*photo.height/photo.width))};invalidate(0);
 }catch(e){console.error(e);$('#status').textContent='启动失败：'+e.message;$('#loading').hidden=true;}}
init();
